"""attachments and disappearing messages

Revision ID: da613aad46a3
Revises: 0001_initial
Create Date: 2026-09-08 00:55:39.643122
"""
from alembic import op
import sqlalchemy as sa

import app.db.base  # noqa: F401  (custom UTCDateTime column type)


revision = '0002_attachments_disappearing'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=True))

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disappear_seconds', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', app.db.base.UTCDateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_messages_expires_at'), ['expires_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_expires_at'))
        batch_op.drop_column('expires_at')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('disappear_seconds')

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
